export const ADD_MOVIE_START = 'ADD_MOVIE_START';
export const EDIT_MOVIE_START = 'EDIT_MOVIE_START';
export const DELETE_MOVIE_START = 'DELETE_MOVIE_START';
export const STORE_MOVIES = 'STORE_MOVIES';
export const RESET_MOVIES_MODEL_STATE = 'RESET_MOVIES_MODEL_STATE';
export const CLEAR_MOVIES_MODEL_STATE = 'CLEAR_MOVIES_MODEL_STATE';
